### PR TITLE
Fix/missing success msg

### PR DESCRIPTION
**Pull request by MathieuCoupe**
Updated handleResult() to publish always the same reponse.

Also fixed 'should push copy response to copySubject' test and added new tests to cover 'cbOnSuccess not used' case.

### CODE REVIEW

**Review by maxisam — APPROVED** [review]
LGTM

**Comment by maxisam** [comment]
@MathieuCoupe Could you test https://www.npmjs.com/package/ngx-clipboard/v/15.1.0-beta01

Thanks!

**Comment by MathieuCoupe** [comment]
Tested 15.1.0-beta01 with my app, it's working fine !

**Comment by maxisam** [comment]
@MathieuCoupe  Thanks! 15.1.0 is released

**Pull request merged**
