### PR TITLE
fix: add support for angular 8

### LINKED ISSUE #178: Angular 8 Issue
When I load this module in a project using Angular 8.0.0-rc.0, I am given this error on start

```
WARNING in ./node_modules/ngx-clipboard/fesm5/ngx-clipboard.js 239:63-71
"export 'DOCUMENT' was not found in '@angular/platform-browser'

WARNING in ./node_modules/ngx-clipboard/fesm5/ngx-clipboard.js 242:159-167
"export 'DOCUMENT' was not found in '@angular/platform-browser'
```

On the previous version of the Angular 8 beta (14), this package worked fine, but on this version it has some issues.

### PR DESCRIPTION
**Pull request by mattlewis92**
Firstly, thanks for your work on this library! 😄 This PR migrates the import to be from common instead, it's been there [since v6](https://v6.angular.io/api/common/DOCUMENT) which is the minimum version this lib supports, so it shouldn't be a breaking change.

Fixes #178

### CODE REVIEW

**Comment by ryan-bradford** [comment]
Thanks for doing this Matt! I was gonna try, but I couldn't find the time.

Do we need to update the peer dependencies in /ngx-clipboard for the project to include Angular 8?

**Comment by mattlewis92** [comment]
It should be fine, `>=6.0.0` will match anything above 7.0: https://github.com/maxisam/ngx-clipboard/blob/master/projects/ngx-clipboard/package.json#L28

**Comment by maxisam** [comment]
@mattlewis92 Could you test it? ngx-clipboard@12.0.1-beta2

Thank for your help!

**Comment by mattlewis92** [comment]
Works for me! 😄

**Comment by maxisam** [comment]
it is on 12.0.1 now Thanks!

**Pull request merged**
