### PR TITLE
Upgrade all dependencies

### PR DESCRIPTION
**Pull request by phra**
This PR will upgrade all the dependencies, including Angular. (`npx npm-check-updates -a`)
I've also fixed typescript compilation by casting a private method to a public one.
It seems that now `keyof` operator only exposes public methods.

### CODE REVIEW

**Comment by maxisam** [comment]
Thank you!

**Comment by phra** [comment]
keep in mind to push it on NPM also! :smile:

**Comment by phra** [comment]
i saw that the CI launched semantic-release but on NPM i stil see the old package.. https://www.npmjs.com/package/ngx-clipboard

**Comment by maxisam** [comment]
Yeah, I think because none of the commit titles starts with "fix:", I will fix it later.

**Comment by phra** [comment]
ok, thanks!

**Comment by maxisam** [comment]
8.1.2 is out. Thank you for your help!

**Pull request merged**
